name: CI

on: push

jobs:
  compile:
    runs-on: ubuntu-16.04
    steps:

      - name: Downgrade OpenSSL
        run: |
          openssl version
          curl https://www.openssl.org/source/openssl-1.0.2g.tar.gz | tar xz && cd openssl-1.0.2g && sudo ./config && sudo make && sudo make install
          sudo ln -sf /usr/local/ssl/bin/openssl `which openssl`
          openssl version
      - name: Compile yara
          # sudo apt-get install python2.7
          # sudo apt-get install cmake
        run: |
          openssl version
          sudo apt-get install automake libtool make gcc pkg-config
          git clone https://github.com/VirusTotal/yara.git yara-source
          cd yara-source
          ./bootstrap.sh
          ./configure
          make
          ls -al
          ls -al libyara/.libs
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            yara-source/yara
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}