name: CI

on: push

jobs:
  compile:
    runs-on: ubuntu-16.04
    steps:

      - name: Downgrade OpenSSL
        run: |
          openssl version
          curl https://www.openssl.org/source/openssl-1.0.2g.tar.gz | tar xz && cd openssl-1.0.2g && sudo ./config && sudo make && sudo make install
          sudo ln -sf /usr/local/ssl/bin/openssl `which openssl`
          openssl version
      - name: Compile yara
          # sudo apt-get install python2.7
          # sudo apt-get install cmake
          #  --host=x86_64-w64-mingw32
          # libssl-dev=1.0.2g-1ubuntu4
        run: |
          openssl version
          sudo apt-get install gcc-mingw-w64 automake libtool libssl-dev=1.0.2g-1ubuntu4 make gcc pkg-config
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install gcc-7 g++-7
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
          wget https://github.com/VirusTotal/yara/archive/v4.0.5.tar.gz
          tar -zxf v4.0.5.tar.gz
          cd yara-4.0.5
          sudo ./bootstrap.sh
          sudo ./configure
          sudo make
          ls -al
          ls -al libyara/.libs
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            yara-4.0.5/yara
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}